# Youtube Trending Videos - Data Analysis Project

---

### **Course:** Foundation of Computer Science
### **Academic Year:** 2025/2026
### **Project Author:** Camila Alexandra Alanya Abia (Matricola: 846575)

---

## Project Overview
This Jupyter Notebook contains the complete end-to-end data analysis pipeline for the YouTube Trending Videos dataset. The project covers advanced data cleaning, chronological sorting, modular vectorization, hierarchical JSON parsing, and multi-variable statistical aggregations across 10 different countries.

## 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [1]:
import pandas as pd

Since the Japanese, Korean, Mexico and Russian datasets natively contain non-Western scripts, they are generally compatible with UTF-8. However, to prevent the code from crashing due to a few isolated invalid bytes or hidden formatting errors, we explicitly set `encoding='utf-8'` and utilized `encoding_errors='replace'`.

In [2]:
CA_videos = pd.read_csv("data/CAvideos.csv")
DE_videos = pd.read_csv("data/DEvideos.csv")
FR_videos = pd.read_csv("data/FRvideos.csv")
GB_videos = pd.read_csv("data/GBvideos.csv")
IN_videos = pd.read_csv("data/INvideos.csv")
JP_videos = pd.read_csv("data/JPvideos.csv", encoding='utf-8', encoding_errors='replace')
KR_videos = pd.read_csv("data/KRvideos.csv", encoding='utf-8', encoding_errors='replace')
MX_videos = pd.read_csv("data/MXvideos.csv", encoding='utf-8', encoding_errors='replace')
RU_videos = pd.read_csv("data/RUvideos.csv", encoding='utf-8', encoding_errors='replace')
US_videos = pd.read_csv("data/USvideos.csv")

In [3]:
CA_videos['country'] = 'CA'
DE_videos['country'] = 'DE'
FR_videos['country'] = 'FR'
GB_videos['country'] = 'GB'
IN_videos['country'] = 'IN'
JP_videos['country'] = 'JP'
KR_videos['country'] = 'KR'
MX_videos['country'] = 'MX'
RU_videos['country'] = 'RU'
US_videos['country'] = 'US'

In [4]:
# We use ignore_index=True to reset the index of the final concatenated DataFrame. 
# Since each country's DataFrame has its own index starting from 0, combining them without this parameter would result in duplicated indices. 

df = pd.concat([CA_videos,DE_videos,FR_videos,GB_videos,IN_videos,JP_videos,KR_videos,MX_videos,RU_videos,US_videos], ignore_index= True)
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375942 entries, 0 to 375941
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                375942 non-null  object
 1   trending_date           375942 non-null  object
 2   title                   375942 non-null  object
 3   channel_title           375942 non-null  object
 4   category_id             375942 non-null  int64
 5   publish_time            375942 non-null  object
 6   tags                    375942 non-null  object
 7   views                   375942 non-null  int64
 8   likes                   375942 non-null  int64
 9   dislikes                375942 non-null  int64
 10  comment_count           375942 non-null  int64
 11  thumbnail_link          375942 non-null  object
 12  comments_disabled       375942 non-null  bool
 13  ratings_disabled        375942 non-null  bool
 14  video_error_or_removed  375942 non-null  bool
 15  description             356464 non-null  object
 16  country                 375942 non-null  object
dtypes: bool(3), int64(5), object(9)
memory usage: 41.2+ MB

## 2. Extract all videos that have no tag.

Based on an initial data exploration using `df.info()`, we observed that the `tags`column contains zero missing values. Therefore, to extract all videos with no tags, we simply filtered the Dataframe for rows where the `tags`column explicity equals the string `"[none]"`.

In [6]:
no_tag = df[df['tags'] == '[none]']
no_tag.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA

## 3. For each channel, determine the total number of views

By inspecting the dataset, we observe that the `views` column is cumulative. A video can remain in the trending section for multiple consecutive days, creating a new row for each day it trends within a specific country. If we were to simply use `.groupby('channel_title')['views'].sum()`, we would sum the views of the same video multiple times, leading to heavily inflated and incorrect totals.


Look at Great Britain (GB): the video trended from November 14th all the way to November 27th, and the views grew from 33 million to over 138 million.

In [7]:
df[(df['video_id']=='2Vv-BfVoq4g')&(df['country'] == 'GB')][['trending_date','title','views','country']]

,trending_date,title,views,country
122451,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,GB
122673,17.15.11,Ed Sheeran - Perfect (Official Music Video),39082222,GB
122885,17.16.11,Ed Sheeran - Perfect (Official Music Video),43449654,GB
123130,17.17.11,Ed Sheeran - Perfect (Official Music Video),48461709,GB
123340,17.18.11,Ed Sheeran - Perfect (Official Music Video),56525948,GB
123548,17.19.11,Ed Sheeran - Perfect (Official Music Video),65651096,GB
123758,17.20.11,Ed Sheeran - Perfect (Official Music Video),74009550,GB
123971,17.21.11,Ed Sheeran - Perfect (Official Music Video),82143174,GB
124178,17.22.11,Ed Sheeran - Perfect (Official Music Video),91081966,GB
124412,17.23.11,Ed Sheeran - Perfect (Official Music Video),100488035,GB
124622,17.24.11,Ed Sheeran - Perfect (Official Music Video),109625533,GB
124832,17.25.11,Ed Sheeran - Perfect (Official Music Video),119263821,GB
125036,17.26.11,Ed Sheeran - Perfect (Official Music Video),129460449,GB
125239,17.27.11,Ed Sheeran - Perfect (Official Music Video),138578860,GB

To obtain the correct number of total views for each channel, we implement the following strategy:

1. We convert `trending_date` into a proper datetime object

In [8]:
df['trending_date'] = pd.to_datetime(df['trending_date'], format = '%y.%d.%m')

2. We sort the DataFrame by `country` and `trending_date` in ascending order.

In [9]:
df_sorted = df.sort_values(by=['country', 'trending_date'])
df_sorted.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

3. Since views are cumulative, the last occurrence of a video in a given country contains its final and maximum view count.

In [10]:
df_unique_videos = df_sorted.drop_duplicates(subset = ['video_id', 'country'], keep= 'last')
df_unique_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,0yIWz1XEeyc,2017-11-14,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,25,2017-11-13T07:37:51.000Z,"#DramaAlert|""Drama""|""Alert""|""DramaAlert""|""keem...",1309699,103755,4613,12143,https://i.ytimg.com/vi/0yIWz1XEeyc/default.jpg,False,False,False,► Follow for News! - https://twitter.com/KEEMS...,CA
12,FyZMnhUtLfE,2017-11-14,猎场 | Game Of Hunting 12【TV版】（胡歌、張嘉譯、祖峰等主演）,大劇獨播,1,2017-11-12T16:00:01.000Z,"電視劇|""大陸電視劇""|""猎场""|""职场""|""商战""|""爱情""|""都市""|""胡歌""|""陈龙""...",158815,218,30,186,https://i.ytimg.com/vi/FyZMnhUtLfE/default.jpg,False,False,False,Thanks for watching the drama! Help more peopl...,CA
13,7MxiQ4v0EnE,2017-11-14,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11T16:41:15.000Z,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,8063,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,CA
16,gifPYwArCVQ,2017-11-14,Fake Pet Smart Employee Prank!,NELK,23,2017-11-13T01:30:01.000Z,"prank|""pranks""|""nelk""|""nelkfilmz""|""nelkfilms""",557883,44558,621,9619,https://i.ytimg.com/vi/gifPYwArCVQ/default.jpg,False,False,False,3 Days left to cop NELK merch: https://nelk.ca...,CA
17,8NHA23f7LvU,2017-11-14,Jason Momoa Wows Hugh Grant With Some Dothraki...,The Graham Norton Show,24,2017-11-10T19:06:23.000Z,"Graham Norton|""Graham Norton Show Official""|""E...",1496225,16116,236,605,https://i.ytimg.com/vi/8NHA23f7LvU/default.jpg,False,False,False,I think Sarah Millican was very excited for th...,CA

4. Finally, we group the deduplicated data by `channel_title` and sum the unique final views.

In [11]:
channel_views = df_unique_videos.groupby('channel_title', as_index=False)['views'].sum()
channel_views

                channel_title    views
0                  ! 세상에 무슨일이  1052789
1               !!8時だよ面白ネタ大集合    50207
2              !BTS・TWICE まとめ     7310
3      !Los amorosos Virales¡     6069
4                     !t Live   240038
...                       ...      ...
37581              ５分でできる DIY   183245
37582                  ＢＡＳＨｔｖ   116292
37583           Ｋのフィッシングちゃんねる    37165
37584                 ＷＡＪＯＩＫＡ   424129
37585                💜Sandrea   188204

[37586 rows x 2 columns]

## 4. Save all rows with disabled comments and disabled ratings, or that have `video_error_or_removed` in a new dataframe called `excluded`, and remove those rows from the original dataframe.

In [12]:
df.shape

(375942, 17)

In [13]:
excluded = df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]
excluded.shape

(2620, 17)

In [14]:
df_clean = df.drop(excluded.index)

In [15]:
df_clean.shape

(373322, 17)

## 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

To calculate the `like_ratio`, we need to divide the number of likes by the number of dislikes ($likes / dislikes$). However, a preliminary analysis of the dataset revealed 7,387 rows where the number of dislikes is exactly 0.

In [16]:
# Controlliamo se ci sono video con 0 dislikes o valori mancanti
(df_clean['dislikes'] == 0).sum()

np.int64(7387)

In [17]:
df_clean[['likes', 'dislikes']].isna().sum()

likes       0
dislikes    0
dtype: int64

We use `numpy.where()`:
- For all rows where `dislikes > 0`, the standard ratio is computed.
- For rows where `dislikes == 0`, we explicitly assign a `NaN` (Not a Number) value.

In [18]:
import numpy as np

In [19]:
df_clean['like_ratio'] = np.where(
    df_clean['dislikes'] > 0,
    df_clean['likes'] / df_clean['dislikes'],
    np.nan
)

In [20]:
df_clean[['likes', 'dislikes', 'like_ratio']].head()

     likes  dislikes  like_ratio
0   787425     43420   18.135076
1   127794      1688   75.707346
2   146035      5339   27.352500
3   132239      1989   66.485168
4  1634130     21082   77.513044

In [21]:
df_clean['like_ratio'].isna().sum()

np.int64(7387)

## 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [22]:
df_clean['publish_time'] = pd.to_datetime(df_clean['publish_time'])

In [23]:
def cluster_10min_interval(timestamp):
    start_time = timestamp.dt.floor('10min') #timestamp rounded to the closet 10 minute boundary
    end_time = start_time + pd.Timedelta(minutes = 10)
    return start_time.dt.strftime('%H:%M') + ' - ' + end_time.dt.strftime('%H:%M') 
df_clean['interval'] = cluster_10min_interval(df_clean['publish_time'])

In [24]:
df_clean[['publish_time','interval']]

                    publish_time       interval
0      2017-11-10 17:00:03+00:00  17:00 - 17:10
1      2017-11-13 17:00:00+00:00  17:00 - 17:10
2      2017-11-12 19:05:24+00:00  19:00 - 19:10
3      2017-11-12 18:01:41+00:00  18:00 - 18:10
4      2017-11-09 11:04:14+00:00  11:00 - 11:10
...                          ...            ...
375937 2018-05-18 13:00:04+00:00  13:00 - 13:10
375938 2018-05-18 01:00:06+00:00  01:00 - 01:10
375939 2018-05-18 17:34:22+00:00  17:30 - 17:40
375940 2018-05-17 17:00:04+00:00  17:00 - 17:10
375941 2018-05-17 17:09:38+00:00  17:00 - 17:10

[373322 rows x 2 columns]

## 7. For each interval, determine the number of videos, average number of likes and of dislikes.

Since a single video accumulates rows every day it remains in the trending section, performing an evaluation on the raw dataset would heavily distort the true number of unique videos published in each time slot. To prevent this bias, we drop chronological duplicates using `subset=['video_id', 'country']`, keeping only the final snapshot of each video.

In [25]:
df_unique_analysis = df_clean.sort_values(by=['country', 'trending_date']).drop_duplicates(subset=['video_id','country'], keep='last')

Using the `.agg()` function, we simultaneously compute the total count of unique videos (`count`) and the mathematical averages (`mean`) for both likes and dislikes within each specific time slot.

In [26]:
interval_analysis = df_unique_analysis.groupby('interval', as_index=False).agg(
    number_videos = ('video_id', 'count'),
    average_likes = ('likes', 'mean'),
    average_dislikes = ('dislikes', 'mean')
)
interval_analysis

          interval  number_videos  average_likes  average_dislikes
0    00:00 - 00:10           1477   19168.063643       1541.983074
1    00:10 - 00:20            830   11767.301205        540.801205
2    00:20 - 00:30            702   11223.434473        775.698006
3    00:30 - 00:40            890   11602.526966        461.494382
4    00:40 - 00:50            680   11661.539706        807.560294
..             ...            ...            ...               ...
139  23:10 - 23:20            882   10428.346939        754.888889
140  23:20 - 23:30            809   14867.259580        739.637824
141  23:30 - 23:40            998    9825.811623        585.886774
142  23:40 - 23:50            836   12600.630383       1361.488038
143  23:50 - 00:00            736    6567.497283        437.184783

[144 rows x 4 columns]

## 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags.

The `tags` column contains a structured string where multiple keywords for a single video are concatenated using the pipe delimiter (`|`).

In [27]:
df_unique_tags = df_clean.sort_values(by=['country', 'trending_date']).drop_duplicates(subset=['video_id','country'], keep='last')

We sanitize the strings by removing double quotes and applying `.str.split('|')`. This converts the flat text into a Python list of discrete tag strings.

In [28]:
# remove unwanted characters like quotes, and split the string into a list of tags using the pipe '|' separator
df_unique_tags['tags'] = df_unique_tags['tags'].str.replace('"','').str.split('|')

We apply the `.explode('tags')` method. This operation transforms each element of the tag lists into a separate row, maintaining the correct relationship with the original video identifiers.

In [29]:
# Explode the list of tags so each individual tag gets its own row
df_exploded_tags = df_unique_tags.explode('tags')
df_exploded_tags = df_exploded_tags[(df_exploded_tags['tags'] != '[none]') & ((df_exploded_tags["tags"] != ""))]

In [30]:
tag_counts = df_exploded_tags.groupby('tags', as_index=False)['video_id'].count()
tag_counts.columns = ['tag', 'number_of_videos'] # rename columns
tag_counts

                                                    tag  number_of_videos
0                                           #Freeticket                 1
1                                                 #GST                  1
2                                            #Jaisimha                  1
3                                       #JanaSenaParty                  1
4                                            #MahaaNews                 1
...                                                 ...               ...
844045                                                😥                 1
844046                 😭 #résistancelamaindesqueezie ❤️                 1
844047  😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية                 1
844048                              🚀 smartpixel.com.ua                 1
844049                     🤝 ZARBEX zahlt Schutzgeld!!!                 1

[844050 rows x 2 columns]

## 9. Find the tags with the largest number of videos

In [31]:
top_tags = tag_counts.sort_values(by='number_of_videos', ascending= False).head(10)
top_tags

               tag  number_of_videos
12717         2018              6530
354123       funny              5965
294641      comedy              4494
464429        news              3493
12368         2017              3122
583372       video              2600
532759        show              2402
382186       humor              2338
557337  television              2106
573751          tv              2063

## 10. For each (tag, country) pair, compute average ratio likes/dislikes

We reuse the `df_exploded_tags` DataFrame from Step 8. Since this dataset contains a single tag per row while maintaining the original `country` and `like_ratio` attributes, it serves for this multi-variable analysis.

In [32]:
df_exploded_tags.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country', 'like_ratio',
       'interval'],
      dtype='object')

In [33]:
tag_country_ratio = df_exploded_tags.groupby(['tags','country'], as_index=False)['like_ratio'].mean()
tag_country_ratio.columns = ['tag', 'country', 'average_like_ratio']
tag_country_ratio.head()

                tag country  average_like_ratio
0       #Freeticket      IN            2.654905
1             #GST       IN            2.416896
2        #Jaisimha       IN            2.654905
3   #JanaSenaParty       IN           17.134058
4        #MahaaNews      IN            8.325203

## 11. For each (trending_date, country) pair, the video with the largest number of views


To pinpoint the exact video that dominated the platform each day within each region, we need to extract full rows containing the maximum value of `views` for every distinct combination of `trending_date` and `country`.

We group the dataset by `['trending_date', 'country']` and apply `.idxmax()` on the `views` column. This function identifies the precise row index where the maximum view count occurs within each sub-group.

In [34]:
max_views_indices = df_clean.groupby(['trending_date','country'])['views'].idxmax()
max_views_indices.head(10)

trending_date  country
2017-11-14     CA              4
               DE          40912
               FR          81895
               GB         122451
               IN         161378
               KR         219394
               MX         253980
               RU         294429
               US         335063
2017-11-15     CA            282
Name: views, dtype: int64

We pass these discovered indices into the `.loc[]` accessor, pulling the complete records from our DataFrame

In [35]:
top_videos_per_day = df_clean.loc[max_views_indices]
top_videos_per_day = top_videos_per_day[['trending_date', 'country', 'video_id', 'title', 'channel_title', 'views']]
top_videos_per_day.reset_index(drop=True).head(10)

,trending_date,country,video_id,title,channel_title,views
0,2017-11-14,CA,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622
1,2017-11-14,DE,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622
2,2017-11-14,FR,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622
3,2017-11-14,GB,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622
4,2017-11-14,IN,ePO5M5DE01I,Tiger Zinda Hai | Official Trailer | Salman Kh...,YRF,35885754
5,2017-11-14,KR,n1WpP7iowLc,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,17158579
6,2017-11-14,MX,JzCsM1vtn78,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,4477587
7,2017-11-14,RU,U_4BLnJuR3g,12 лайфхаков с термоклеем для хендмейда,Трум Трум,2109573
8,2017-11-14,US,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622
9,2017-11-15,CA,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,39082222

## 12. Divide trending_date into three columns: year, month, day

In [36]:
df_clean['year'] = df_clean['trending_date'].dt.year
df_clean['month'] = df_clean['trending_date'].dt.month
df_clean['day'] = df_clean['trending_date'].dt.day

df_clean[['trending_date', 'year', 'month', 'day']].head()

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

## 13. For each (month, country) pair, the video with the largest number of views

same logic as step 11

In [37]:
max_views_indices_month_contry = df_clean.groupby(['month','country'])['views'].idxmax()
top_videos_per_month = df_clean.loc[max_views_indices_month_contry]
top_videos_per_month = top_videos_per_month[['month', 'country', 'video_id', 'title', 'channel_title', 'views']].reset_index(drop=True)
top_videos_per_month.head(10)

,month,country,video_id,title,channel_title,views
0,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,43067983
1,1,DE,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
2,1,FR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
3,1,GB,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,90598955
4,1,IN,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,42019590
5,1,KR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
6,1,MX,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,31680160
7,1,RU,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,23198594
8,1,US,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,57951412
9,2,CA,xpVfcZ0ZcFM,Drake - God’s Plan,DrakeVEVO,47362934

## 14. Read all json files with the video categories

In [38]:
import json
import os

To aggregate all country categories into a single DataFrame named `totjson`, we implement an automated loop pipeline:
1. We loop through a defined list of target country codes to dynamically construct the file paths.
2. Since JSON is nested, we apply `pd.json_normalize()` directly to the `items` series. This flattens properties like `snippet.title` and `snippet.assignable` into proper tabular columns.
3. Before merging, we append a `country` column to each individual sub-table to track the geographic origin of those categories.
4. Finally, we utilize `pd.concat()` to bind all 10 DataFrames together.

In [39]:
json_folder = "json"
countries = ['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
json_df = []

for country in countries:
    file_path = os.path.join(json_folder, f"{country}_category_id.json")
    raw_json = pd.read_json(file_path)
    df_normalized = pd.json_normalize(raw_json['items'])
    df_normalized['country'] = country
    json_df.append(df_normalized)

totjson = pd.concat(json_df, ignore_index=True)
totjson

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
307,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
308,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
309,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
310,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

## 15. For each country, determine how many videos have a category that is not assignable.

In [40]:
not_assignable = totjson[totjson['snippet.assignable'] == False].groupby('country').size().reset_index(name='unassignable_count')
not_assignable

  country  unassignable_count
0      CA                  17
1      DE                  17
2      FR                  17
3      GB                  17
4      IN                  17
5      JP                  17
6      KR                  17
7      MX                  17
8      RU                  17
9      US                  17